### ISSUE TITLE
Make currency list editable via hook

### ISSUE THREAD

**Issue by andyplak** [andyplak/events-manager-currency-per-event#2]
Thus allowing people to reduce or expand the default list.

**Comment by mike-leber** [comment]
Any, what would be a manual step to do this for the moment? Just adding a new currency to the array? Let's say I took Indian Rupees, going for INR and its description, would the rest of the event manager system recognize this? Would Paypal gateway recognize this? (-> crap, Paypal does not handle Rupees anyway ;))

**Comment by andyplak** [comment]
Hi Mike,

As you've spotted, unfortunately PayPal do not support Rupees:
[official list of supported currencies](https://developer.paypal.com/docs/classic/api/currency_codes/#paypal).

I've made some changes to the plugin, as if you were to add extra currencies, you would have had to add it here and in Events Manager as well. I now pull the currency list for this plugin directly from Events Manager and if you need to modify them, then you'd just need to hook into Event Manager's `em_get_currencies` filter.

Something like this (untested):

```
<?php

function my_em_get_currencies( $currencies ) {

  $currencies->names['LAK']        = "LAK - Laotian Kip";
  $currencies->symbols['LAK']      = "₭";  // if the currency has a html symbol, put that here i.e. &yen; &pound;
  $currencies->true_symbols['LAK'] = "₭";

  return $currencies;
}
add_filter('em_get_currencies', 'my_em_get_currencies', 10, 1);
```
