### ISSUE TITLE
Notification email does not show selected currency

### ISSUE THREAD

**Issue by mike-leber** [andyplak/events-manager-currency-per-event#3]
Tried to set an event with a currency coming by default with events manager pro. Used HUF. It properly shows in the registration form. A registration also shows with the proper currency symbol within the admin GUI / the list of registrations.

However, for registrations I have set up a custom notification email using the #_BOOKINGSUMMARY placeholder. The displayed currency after registration within the email though does show the EUR symbol, not the HUF symbol.

**Comment by andyplak** [comment]
Hey Mike,

Just to confirm, HUF is the default currency within EM and for some events you've set EUR?
The event in question does not have EUR set, but EUR shows in the email? Or is it the other way around?

**Comment by mike-leber** [comment]
Hi Andy,

EUR is the default currency. Actually tried with adding another custom currency (Rand), assigned it to an event, all data showing Rand (booking form, admin), except the email delivering the default currency (in this case EUR). Tried the same then with HUF for the event in order to verify no issues with my custom currency. Confirmed: same behavior, mail wit BOOKINGSUMMARY delivering EUR

**Comment by andyplak** [comment]
OK, thanks. I'll investigate.

**Comment by andyplak** [comment]
@mike-leber can you give the latest version on the [develop branch](https://github.com/andyplak/events-manager-currency-per-event/tree/develop) a test and see if that works for you?

**Comment by mike-leber** [comment]
Tested. Yes, it works Andy. Thx. One comment: after installing this version there is a warning displayed ("red font") inside admin: "Please ensure both Events Manager and Events Manager Pro are enabled for the Currencies per Event plugin to work." Not sure, what has to be done at Events Manager / Pro.

**Comment by andyplak** [comment]
@mike-leber Try again now (develop branch). I'd added that check quite recently, but was running the check before Events Manager had been loaded.

**Comment by mike-leber** [comment]
Tried. Check message gone. Works fine. Thx a lot Andy!
